/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Clases.Aula;
import Clases.Docente;
import Modelo.AulaDAO;
import Modelo.DocenteDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class CI_Aula extends javax.swing.JFrame {

    //CREACION DE VARIABLES GLOBALES
    int ginst;
    int seccion;
    public CI_Aula() {
        initComponents();
        setLocationRelativeTo(null);
        cbCurso.setVisible(false);
        cbCurso1.setVisible(false);
        lbcs.setVisible(false);
        lbcp.setVisible(false);
        Docente docente = new Docente();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cb_gradoInstruccion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        cbProfesores = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        lbcp = new javax.swing.JLabel();
        cbCurso = new javax.swing.JComboBox<>();
        cbCurso1 = new javax.swing.JComboBox<>();
        lbcs = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cbgrado = new javax.swing.JComboBox<>();
        cbseccion = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        btnAgregarAula = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("ASIGNACION DE AULA");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jLabel2.setText("Grado de Instruccion:");

        cb_gradoInstruccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Seleccione---", "Primaria", "Secundaria" }));
        cb_gradoInstruccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_gradoInstruccionActionPerformed(evt);
            }
        });

        jLabel3.setText("Profesores:");

        cbProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProfesoresActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Materia", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbcp.setText("Cursos de Primaria:");
        jPanel2.add(lbcp, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        cbCurso.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Comunicacion", "Matematica", "Razonamiento Verbal", "Razonamiento Matematico", "Ciencias Sociales", "Ciencia y Ambiente", "Ingles", "Persona Familia y Relaciones Humanas", "Educacion Fisica", "Historia", "Educacion Civica" }));
        jPanel2.add(cbCurso, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, 30));

        cbCurso1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cbCurso1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cursos de 1ro", "Cursos de 2do", "Cursos de 3ro", "Cursos de 4to", "Cursos de 5to", "Cursos de 6to" }));
        jPanel2.add(cbCurso1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 160, 30));

        lbcs.setText("Cursos de Secundaria:");
        jPanel2.add(lbcs, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Aula", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        jLabel6.setText("Grado:");

        jLabel7.setText("Seccion:");

        cbgrado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        cbgrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbgradoActionPerformed(evt);
            }
        });

        cbseccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D" }));
        cbseccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbseccionActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/aula.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbseccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbgrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(111, 111, 111))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cbgrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbseccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel5)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        btnAgregarAula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregarAula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevo.png"))); // NOI18N
        btnAgregarAula.setText("AGREGAR");
        btnAgregarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAulaActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/salir3.png"))); // NOI18N
        jButton1.setText("SALIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cb_gradoInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(346, 346, 346))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(btnAgregarAula, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cb_gradoInstruccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbProfesores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregarAula, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jPanel2.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb_gradoInstruccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_gradoInstruccionActionPerformed
        DocenteDAO dao = new DocenteDAO();
        String gi = cb_gradoInstruccion.getSelectedItem().toString();
            cbProfesores.removeAllItems();   //eliminar el contenido del combo box   
        if (gi.equalsIgnoreCase("Primaria")) {
            cbCurso.setVisible(false);
            cbCurso1.setVisible(true);
            lbcs.setVisible(false);
            lbcp.setVisible(true);
            ginst = 1;
            dao.ListarDocentes(cbProfesores, ginst);
            
        }
        if (gi.equalsIgnoreCase("Secundaria")) {
            cbCurso.setVisible(true);
            cbCurso1.setVisible(false);
            lbcs.setVisible(true);
            lbcp.setVisible(false);
            ginst = 2;
            dao.ListarDocentes(cbProfesores, ginst);
            
        }
    }//GEN-LAST:event_cb_gradoInstruccionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
        CI_Menu menu = new CI_Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnAgregarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarAulaActionPerformed
        Aula aula = new Aula();
        AulaDAO au = new AulaDAO();      
        //Recogemos los datos para su proxima INSERT
        String grado_instruccion = cb_gradoInstruccion.getSelectedItem().toString();
        int grado = Integer.parseInt(cbgrado.getSelectedItem().toString());
        String curso = cbCurso.getSelectedItem().toString();
        String cursop=cbCurso1.getSelectedItem().toString();
        int index = cbProfesores.getItemAt(cbProfesores.getSelectedIndex()).getCoddoc();//Recepcionamos el ID del docente Seleccionado
        if(grado_instruccion.equalsIgnoreCase("Primaria")){
            aula.setCurso(cursop);
            aula.setIdgrado(grado);
            aula.setIdseccion(seccion);
            aula.setIddocente(index);
            au.AgregarAula(aula);
        }
        else{
            aula.setCurso(curso);
            aula.setIdgrado(grado);
            aula.setIdseccion(seccion);
            aula.setIddocente(index);
            au.AgregarAula(aula);
        }
    }//GEN-LAST:event_btnAgregarAulaActionPerformed
    
    private void cbProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProfesoresActionPerformed
       // txtCodD.setText(cbProfesores.getItemAt(cbProfesores.getSelectedIndex()).getCoddoc() + "");
    }//GEN-LAST:event_cbProfesoresActionPerformed

    private void cbgradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbgradoActionPerformed
        
    }//GEN-LAST:event_cbgradoActionPerformed

    private void cbseccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbseccionActionPerformed
        String sec = cbseccion.getSelectedItem().toString();
        switch(sec){
           case "A": seccion=1;break;
           case "B": seccion =2; break;
           case "C": seccion=3; break;
           case "D": seccion=4; break;
       }
    }//GEN-LAST:event_cbseccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CI_Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CI_Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CI_Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CI_Aula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CI_Aula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarAula;
    private javax.swing.JComboBox<String> cbCurso;
    private javax.swing.JComboBox<String> cbCurso1;
    private javax.swing.JComboBox<Docente> cbProfesores;
    private javax.swing.JComboBox<String> cb_gradoInstruccion;
    private javax.swing.JComboBox<String> cbgrado;
    private javax.swing.JComboBox<String> cbseccion;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbcp;
    private javax.swing.JLabel lbcs;
    // End of variables declaration//GEN-END:variables
}
